# Generated by Django 4.2.16 on 2024-11-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_gateway_mission_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway_el',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
