# Generated by Django 4.2.16 on 2024-11-16 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gateway', '0007_alter_gateway_mission_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway_el',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gateway_mission',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
