# Generated by Django 4.2.16 on 2024-11-17 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gateway', '0009_alter_gateway_el_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway_mission',
            name='creator',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
